### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by 26789564** [crazyliuxp/ngx-editor.md-markdown#1]
图片无法上传该怎么解决？

**Comment by crazyliuxp** [comment]
你有配置自己的图片上传地址吗？

2019-09-07 21:17 GMT+08:00, zj <notifications@github.com>:

**Comment by 26789564** [comment]
我这边运行您的代码，图片无法上传，能提供一个图片上传的解决方案吗？
具体在哪配置图片上传地址？
谢谢

**Comment by crazyliuxp** [comment]
src/app/editor/model/editor-config.ts 这个文件中有个  imageUploadURL 图片上传地址的配置。

zj <notifications@github.com> 于2019年9月9日周一 下午8:23写道：
